name: sce_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pip
  - flake8
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - plotly
  - matplotlib-base
  - hdbscan
  - h5py
  - pp-sketchlib >=1.7.0
  - pybind11 >= 2.12.0
  - zlib
  - cmake >= 3.19
  - libgomp
  - tqdm
  - ffmpeg
