name: Build and run tests

on: [push]

env:
  ENV CONDA_OVERRIDE_ARCHSPEC: "skylake"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Conda environment from environment.yml
      env:
        ENV CONDA_OVERRIDE_ARCHSPEC: "skylake"
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: sce_env
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install and run_test.py
      shell: bash -el {0}
      run: |
        python -m pip install -v .
        cd test && python run_test.py
